[package]
name = "actix-test"
version = "0.1.0"
authors = []
edition = "2018"


[dependencies]
actix-web = { version =  "3" }
actix-files = { version = "0.5.0" }
actix = "0.10"
actix-web-actors = "3"

[profile.release]
# symbols are nice and they don't increase the size on Flash
debug = true
